name: lala

services:
  lala:
    container_name: lala
    image: un000nu/${IMAGE_NAME}
    platform: linux/amd64
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]  # select one GPU
        limits:
          cpus: "31.0"
          memory: 12g
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    stop_signal: SIGINT
    stop_grace_period: 15s
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"